### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by blaise-io** [iceddev/node-chromify#3]
I cannot get it to work, and I think it has to do with me not following the instructions correctly. (they're a bit minimal)

What I did:
1. Installed Chrome Canary
2. Navigated to chrome://extensions/ and clicked the Load Unpacked Extension button
3. Selected the folder `example/plugin`
4. Opened `example/full/index.html` and pressed the Go button
5. Quickly opened 2 tabs with `http://127.0.0.1:1337/` 

Tried 4 and refreshing localhost tabs a couple of times, without success.

In the tabs with 127.0.0.1:1337, I get `Oops! Google Chrome could not connect to 127.0.0.1:1337` and in index.html, console:

``` js
Object {title: "browser", browser: true, env: Object, argv: Array[0]}
EventEmitter: function () {}
argv: Array[0]
binding: function (name) {
browser: true
chdir: function (dir) {
cwd: function () { return cwd }
env: Object
nextTick: function nextTick(fn) {
title: "browser"
__proto__: Object
```

Am I doing something wrong?

**Comment by phated** [comment]
It seems that you chose the "full" example which is actually just a debug build of node-chromify. Try using the "plugin" example.  I will be renaming them to "debug" and "http" today to forgo any confusions the current naming scheme may cause.
